### ISSUE TITLE
Setup Amazon Relational Database

### ISSUE THREAD

**Issue by Rubenvdbrink** [HU-ICT-LAB/RobotWars#101]
# Description/Why do we need to do this?
Since our Firebase won't work due to insufficient budget we will need a new option. The only "education tier" free database we have access to is AWS so we will be setting that up in this issue.

# Tasks for this user story 

- [x] Get in contact with Rienk for the aws academy accounts.
- [x] Create the database.
- [x] Setup the database structure.

# Acceptance criteria
When the database is up 'n running.
