### ISSUE TITLE
Research which upgrades can be done to the RoboMaster

### ISSUE THREAD

**Issue by Rubenvdbrink** [HU-ICT-LAB/RobotWars#11]
# Description

This story is about which additional upgrades can be added to the Robomaster S1 using the existing hardware interfaces

# Why do we need to do this?

This story is need for beter understand what is posible with the robomaster without adding a external microcontroller. This is usefull for knowing what kind of modulles can be added on later on the robot wich in turn is needed for planning out future userstories.

# Tasks for this user story 

- [ ] Reseach wether it's possible to add hardware modules to the robot without using an external microcontroller
- [ ] Research wether the UART interface is capable of communicating with external hardware modules
- [ ] Research the capabilities of the onboard Sensor Adapter and which/how many hardware modules can be added with it.

#  Acceptance criteria

The user story is done when all the research topics has been addressed and documented on the wiki

As product owner I want to know which upgrades I can add to the robot and how to add them

**Comment by RichardDev01** [comment]
This userstory is basically done right? @MatthiesBrouwer 
I know there are a few wiki pages now about this topic
