### ISSUE TITLE
Manual data collection from the S1

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#116]
# Description

This story is about gathering data from the S1 on a manual control WITHOUT ROS2.

# Why do we need to do this?

This story is needed for gathering data from the S1 and writing it to the database

# Tasks for this user story 

- [ ] Create link with database from the S1
- [ ] Create logger for the data
- [ ] Write data from the S1 to the database

# Acceptance criteria

This user story is done when there is a link with the database and S1 and there is data from the S1 in the DB.

**Comment by RichardDev01** [comment]
shelved because it is not needed for our project
