### ISSUE TITLE
post /cmd_vel topic messages using the /joy topic messages 

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#118]
# Description

“As a developer, you want messages from the /joy topic to be converted to /cmd_vel topic messages so that they can be used by the S1 as control commands”

# Why do we need to do this?

This story is needed for getting the basics done on controlling the S1 with ROS commandos

# Tasks for this user story 

- [x] Decide which buttons are for the angular and velocity in the cmd_vel
- [x] Create a subscriber who reads the message with every /joy topic post and converts it to cmd_vel messages
- [x] Document the application

# Acceptance criteria

This user story is done when the tasks above are completed and it is documented on the wiki.
