### ISSUE TITLE
Control S1 with controller via ros with the /cmd_vel topics

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#119]
# Description

“As a developer I want to be able to control the chassis and gimbal of the S1 with /cmd_vel topic messages so that the S1 can now execute topic commands via /cmd_vel independent of the message poster”

# Why do we need to do this?

This story is needed for creating small fragments of working commands to control the S1 bit for bit.

# Tasks for this user story 

- [x] Write a publisher to receive and read the /cmd_vel messages
- [x] Control the chassis and gimbal based on the /cmd_vel message content
- [x] Document the application

# Acceptance criteria

This user story is done when the S1 chassis and gimbal can be controlled via topic messages.
