### ISSUE TITLE
Being able to fire S1 blaster with controller via /blast topic

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#120]
# Description

“As a developer I want to be able to fire the blaster of the S1 with /blast topic messages so that the S1 can fire independently from the message poster”

# Why do we need to do this?

This story is needed to make small improvements in the ROS2 deployment.

# Tasks for this user story 

- [ ] Send blast messages on the /blast topic via joystick node 
- [ ] Process in the S1 controller node the functionality to catch and execute the blast topic
- [ ] Document the application

# Acceptance criteria

This user story is done when the S1 can fire via /blast topic via joystick node and it is documented on the wiki
