### ISSUE TITLE
Design a scalable and reusable launch file formation for our multi-node project

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#122]
# Description

“As a developer, I want to design a scalable and reusable launch file formation that allows me to call multiple nodes and configurations without them becoming obsolete after future extensions”

# Why do we need to do this?

This story is needed for making a good launch file for this project that is scalable and reusable thought out this whole project.

# Tasks for this user story 

- [ ] Create an overall launch file tree consisting of multiple reusable files (title only)
- [ ] Draw up a diagram showing this formation
- [ ] Document the formation in a wiki

# Acceptance criteria

This user story is done when there is a good and useable launch file and there is a diagram documented on the wiki
