### ISSUE TITLE
Implement a scalable and reusable launch file formation for our multi-node project

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#123]
# Description

“As a developer, I want a scalable and reusable launch file formation that allows me to call multiple nodes and configurations without them becoming obsolete after future expansions”

# Why do we need to do this?

This story is needed for implementing the launch files for ROS2 for this project

# Tasks for this user story 

- [ ] Write the launch file for the joycon node
- [ ] Write the launch file for the joy_to_twist node
- [ ] Write the launch file for the S1 node
- [ ] Write a launch file that can call other launch files with certain formations
- [ ] Document in the wiki
- [ ] (optional) write other launch files

# Acceptance criteria

This user story is done when all the launch files work and it is tested on the jetson and it documented on the wiki
