### ISSUE TITLE
Update documentation about initializing jetson, installing ROS, the known bugs and what commands are needed

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#124]
# Description

“As a future project group I would like to have a well-arranged documentation with which I can completely initialize a jetson and use it for the project purposes without having to do too much research”

# Why do we need to do this?

This story is needed for creating and improve documentation for the future project group that would like to pick up this project

# Tasks for this user story 

- [x] Document the Docker bug + fix
- [x] Document how to use ROS2 + the startup and usage commands
- [x] Document How to get a device in ROS2
- [x] Document how to control the jetson headless via SSH + GNU screen

# Acceptance criteria

This user story is done when the documentation is up to date
