### ISSUE TITLE
Make and finish Customer Journey Mapping

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#125]
# Description

This story is about creating the Customer Journey map.

# Why do we need to do this?

This story is needed for giving insight into the steps a protentional student takes during the process of choosing an education 

# Tasks for this user story 

- [x] Write out the opportunities for the HU per Customer Journey step
- [x] Write out clear action points per step (what does the potential student do?)
- [x] Write out in clarity with whom the potential student has to deal with per journey step

# Acceptance criteria

This user story is done when it shows which steps the average potential student takes and when the detailed information per step is beneficial and useful for HU during (future) projects.
