### ISSUE TITLE
Make a manual about (restart & start-up) of this project

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#126]
# Description

This story is about writing a clear manual about going further with this project for future project groups.

# Why do we need to do this?

This story is needed for passing on information to the next group

# Tasks for this user story 

- [ ] Merging manuals per specialization
- [ ] Write it clear enough so that the project can be started up more easily, even when no project members are present.
- [ ] Write about potential credentials so no configuration is required.

# Acceptance criteria

This user story is done when there is a manual that provides clarity about what the project entails, how to start it up and how to maintain it.
