### ISSUE TITLE
Update documentation wiki (SD)

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#130]
# Description

This story is about updating the information in the wiki

# Why do we need to do this?

This story is need for updating the wiki information with the correct information

# Tasks for this user story 

- [x] Read all wiki's that are part of the SD tasks
- [x] Updated outdated pages
- [x] Make new wiki page for api 

# Updated pages:
- https://github.com/HU-ICT-LAB/RobotWars/wiki/Connect-multiple-RoboMasters-to-a-single-point
- https://github.com/HU-ICT-LAB/RobotWars/wiki/Connection-between-server-hub-and-frontend
- https://github.com/HU-ICT-LAB/RobotWars/wiki/Database-Comparison
- https://github.com/HU-ICT-LAB/RobotWars/wiki/React-frontend

# Acceptance criteria

This user story is done when the wiki is up to date
