### ISSUE TITLE
Research how we can get live camera feed from the robomasters in the webapp

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#135]
# Description

This story is about getting live camera feeds from the robomasters into the webapp

# Why do we need to do this?

This story is needed for getting to know how you can live feed from the robomasters into the webapp

# Tasks for this user story 

- [x] Lookup how you can play videos in react
- [x] Find a way to stream live video to webapp
- [x] update frontend wiki

# Acceptance criteria

This user story is done when there is enough research done about how we can get live camera feed from the robomasters into a webapp
