### ISSUE TITLE
Localization of the S1 without a Lidar using aruco qr codes basics

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#141]
# Description

As developer I need to create a different way of localization without using the Lidar and I opted with the team for using aruco codes

# Why do we need to do this?

This story is needed because we couldn't get the lidar within time and we needed a different approach to localization the robots.

# Tasks for this user story 

- [x] Printout the aruco codes
- [x] Calibrate the camera with the checker patern
- [x] Make a program that can read the markers and calculate the distance from it

# Acceptance criteria

This user story is done when we have a program that can calculate the distance from the camera of the s1 to the aruco code
