### ISSUE TITLE
Research Custom Replay Buffer

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#142]
# Description

As developers, we need to do research on the possibility of implementing a Custom Replay Buffer, as it is currently not possible to directly add samples to a replay buffer from stable baselines 3.

# Why do we need to do this?

This story is needed because research is required to determine if it is possible to and how it is possible to get a custom replay buffer working so that an openAI Gym environment is not necessary for the implementation.

# Tasks for this user story 

- [x] Do research on the attributes/functionality of the stable baselines 3 replay buffer
- [x] Determine the requirements of implementing a custom replay buffer
- [x] Document in the project wiki

# Acceptance criteria

This user story is done when research into the problems surrounding the stable baselines 3 replay buffer has been completed, the requirements for a custom replay buffers have been documented, differences between the original and custom replay buffers have been documented, and all the aforementioned is available in the project wiki.

**Comment by SwagLag** [comment]
@RichardDev01 wiki page for this user story should be done as well https://github.com/HU-ICT-LAB/RobotWars/wiki/Reinforcement-Learning-Pipeline-Custom-Replay-Buffer

**Comment by RichardDev01** [comment]
good work
