### ISSUE TITLE
Research Prioritised Replay Buffer

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#144]
Prerequisites: [LS] Research Custom Replay Buffer #144 

# Description

As developers, we need to do research on how to implement a prioritised replay buffer; a variant on the normal replay buffer that orders the training samples based on the loss experienced on each sample in order to train more effectively. Additionally, research must point out whether using a prioritised replay buffer in our context would result in a positive effect.

# Why do we need to do this?

This story is needed to determine how a prioritised replay buffer is different from a normal replay buffer in terms of implementation and functionality. Additionally, it is necessary so that research can be done into if this addition is beneficial and worth the development time.

# Tasks

- [ ] Do research on prioritised replay buffers for reinforcement learning algorithms.
- [ ] Determine the effect of a prioritised replay buffer in comparison to a normal replay buffer.
- [ ] Argument why the prioritised replay buffer would be a good feature (or not)
- [ ] Do research on how to implement a prioritised replay buffer

# Acceptance Criteria
This user story is done when the functionality and effect of the prioritised replay buffer has been documented, additionally it has been decided whether the implementation of a prioritised replay buffer adds additional worth to the end solution.
