### ISSUE TITLE
Research Reward Function

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#146]
# Description

As developers, we need to do research into how reward functions exactly work and how we can apply them in our pipeline to prepare training experience for the training process.

# Why do we need to do this?

This story is needed to establish base knowledge about reward functions within RL contexts and to determine one for use within our context (for use in training the SAC RL algorithm).

# Tasks

- [x] Do research on reward functions
- [x] Do research on reward functions in context (with SAC)
- [x] Determine requirements of the reward function for our context
- [x] Document in project wiki

# Acceptance Criteria

This user story is done when research on reward functions has been completed and documented in the project wiki, and it is now known how to implement the reward function into the pipeline.

**Comment by RichardDev01** [comment]
@SwagLag , this should be finished asap this spring

**Comment by SwagLag** [comment]
@RichardDev01 Wiki page is done, can I move the issue to review? https://github.com/HU-ICT-LAB/RobotWars/wiki/Reinforcement-Learning-Reward-Function

**Comment by RichardDev01** [comment]
i have check it, good work
