### ISSUE TITLE
Implement Reward Function pseudo code

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#147]
# Description

As a developer, we need to implement a reward function that evaluates state S and S’ and A, and assigns a reward R based on the previous variables, as assigning a reward R is fundamental to implementing a RL algorithm such as SAC.

Due to a change of the project, this user story works with pseudo code now instead of real code

# Why do we need to do this?

This story is needed for implementing the reward function used in the pipeline

# Tasks

- [x] Analyse the set of test data (annotate what the reward should be) # in pseudo code
- [x] Implement reward function in pipeline # in pseudo code
- [x] Test reward function with new data # in pseudo code

# Acceptance Criteria
~This user story is done when - for testing purposes - a subset of data has been annotated for rewards and a reward function has been implemented that can be mapped over rows from the experience database to produce a workable set of data that can be directed into a replay buffer, which produces satisfactory results.~

This story is down when there is a code file with the pseudo coded needed to create the real reward function for the next group

**Comment by RichardDev01** [comment]
Changed User story to meet new requirements, we dont have real data so we made the user story about pseudo code

**Comment by SwagLag** [comment]
@RichardDev01 altered existing reward function pipeline wiki page with the conceptual pseudocode https://github.com/HU-ICT-LAB/RobotWars/wiki/Reinforcement-Learning-Pipeline-Reward-Function

**Comment by SwagLag** [comment]
whoops
