### ISSUE TITLE
Rework react app

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#151]
# Description

As a user I want an clear and easy-to-use frontend so I can easily use the software. When all of the components are made and implemented in issue/133 we will need a last rework of the whole frontend to make it look nice and clear. This will make the frontend more appealing and easy-to-use.

# Why do we need to do this?
To make the frontend more appealing and easy-to-use.

# Tasks for this user story 
- [x] Ask other people what could be improved.
- [x] Take a good look yourself to see what could be improved.
- [x] Improve things suggested.

# Acceptance criteria
This issue is completed when tasks above are done and when any corresponding wiki pages (https://github.com/HU-ICT-LAB/RobotWars/wiki/React-frontend) are updated.
