### ISSUE TITLE
Research on how to organize a workshop

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#152]
# Description

As Businessmanager i want to know how to organize a workshop/training in order to hold a workshop/training on how to use our product

# Why do we need to do this?

This story is needed to transfer our knowledge to the next project group 

# Tasks for this user story 

- [x] Knowing how to put a logical structure into the training
- [x] Knowing how to spark enthusiasm
- [x] Knowing what information is good to know and what is too complex

# Acceptance criteria

This user story is done when all the tasks above are done
