### ISSUE TITLE
Preparing the training/demo for the client(s) and/or (future) project members

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#153]
# Description

As contractor, I want to have a training or demo for the client(s) and/or (future) project members.

# Why do we need to do this?

This story is needed for having different kind of resources to exchange knowledge.

# Tasks for this user story 

- [ ] The division of roles during the training/demo are clear
- [ ] It is clear which stakeholders will be present
- [ ] Knowing what the purpose is of this training/demo
- [ ] Having enough resources (a free room, presentation screen, whiteboard and markers)

# Acceptance criteria

This user story is done when the tasks above are completed
