### ISSUE TITLE
Making an instruction video on how to use our product (Lasergame Robots)

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#154]
# Description

As contractor, I want a video to keep the knowledge of the product accessible for when we have this project later again

# Why do we need to do this?

We only hold our training once, so it is helpful if we create a video on how to use the Lasergame Robots. This can be used for either our clients or future project groups.

# Tasks for this user story 

- [x] Explaining what kind of hardware is present and how to repair the hardware if needed
- [x] Explaining how the AI aspects work
- [x] Explaining how the database structure has been put together
- [x] Explaining what the future opportunities and optimization possibilities are for a future project team.

# Acceptance criteria

This user story is done when the tasks above are completed and there is a video
