### ISSUE TITLE
Physical training/demo for the client(s) and/or (future) project members

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#155]
# Description

As contractor, I want a physical training/demo for the client(s) and/or (future) project members. During this training, the stakeholder(s) will be informed about the most important subjects that put this project together.

# Why do we need to do this?

This story is needed to exchange information to the client(s) and/or (future) project members

# Tasks for this user story 

- [ ] Task 1 
- [ ]  Explaining what kind of hardware is present and how to repair the hardware if needed
- [ ]  Explaining how the AI aspects work
- [ ] Explaining how the database structure has been put together
- [ ]  Explaining what the future opportunities and optimization possibilities are for a future project team. 

# Acceptance criteria

This user story is done when all tasks above are completed
