### ISSUE TITLE
Research ROS2 TF2

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#156]
# Description

As a developer I want to know what TF2 is in order to have a better view of its usefulness within a simulation, and how I can use it in my own implementation

# Why do we need to do this?

This story is needed to under TF2 and if it is useful for our project

# Tasks for this user story 

- [ ] Research TF2 Static transform broadcaster
- [ ] Research TF2 transform broadcaster
- [ ] Research TF2 Static transform broadcaster 
- [ ] Research TF2 transform broadcaster/listener
- [ ] Research Explore TF2 frames
- [ ] Document this whole process

# Acceptance criteria

This user story is done when the tasks above are completed and documented in the wiki
