### ISSUE TITLE
Research URDF

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#157]
# Description

As a developer I want to know what URDF means to get a better view of its implementation, and how I can use it to simulate my own robot model

# Why do we need to do this?

This story is needed to understand how you can simulate a robot model

# Tasks for this user story 

- [ ] Research URDF robot XML tags 
- [ ] Research URDF link XML tags
- [ ] Research URDF joint XML tags
- [ ] Research URDF Collision and inertia properties
- [ ] Document the process

# Acceptance criteria

This user story is done when the tasks above are completed and documented on the wiki
