### ISSUE TITLE
Research robot_state_publisher

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#158]
# Description

As a developer I would like to know what the robot_state_publisher library contains in order to get a better idea of its usefulness within a simulation, and how I can use it to move our own robot simulation

# Why do we need to do this?

This story is needed to get better insight about how this subject works within the simulation

# Tasks for this user story 

- [ ] Research implementatie van robot_state_publisher
- [ ] Research Onderzoek connectie tussen robot_state_publisher en een URDF model
- [ ] Document the process on the wiki

# Acceptance criteria

This user story is done when the tasks above are completed and documented on the wiki
