### ISSUE TITLE
Learn which technologies can be used for the application.

### ISSUE THREAD

**Issue by Rubenvdbrink** [HU-ICT-LAB/RobotWars#16]
# Description

We want to start games via an app.  Before we can create the app we need to know with what frameworks or technologies we can create the app.

# Why do we need to do this?

This story is needed for interfacing with the robots when we use our own code. During the introduction day, there would be need of a custom application. 

# Tasks for this user story 
- [x] Ask contractor for their opinion (application or webapp)
- [x] Research which programming language is going to be used.
- [x] Research how the app can be connected to the server.

# Acceptance criteria

This story is done when the research topic above has been done and documented on the wiki
