### ISSUE TITLE
Make a manual for assembling the extra parts for the S1

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#164]
# Description

As developer, I want to make a manual for the next project group on how to assemble the extra parts that we created for this project

# Why do we need to do this?

This story is needed to exchange information to the next group.

# Tasks for this user story 

- [x] Write about how to manufacture the extra parts 
- [x] Write about where you can get the materials
- [x] Write about the software used to manufacture the parts

# Acceptance criteria

This user story is done when there is a wiki page about how we created the parts for the robots

**Comment by RichardDev01** [comment]
wiki can be found here
https://github.com/HU-ICT-LAB/RobotWars/wiki/Creating-our-own-extra-parts-for-the-S1-overview
