### ISSUE TITLE
How to control the RoboMaster using an external microcontroller.

### ISSUE THREAD

**Issue by Rubenvdbrink** [HU-ICT-LAB/RobotWars#17]
# Description

This learning story is about how the robot can be controlled using a microcontroller after communication has been established. According to the RoboMaster S1 Developer Guide it should be possible to communicate with the robot using an external microcontroller.
# Why do we need to do this?

This story is needed for understanding how to controll the robomaster using an external microcontroller. With this, we should be able to control the built-in modules, extended modules and obtain video/audio streams. 

# Tasks for this user story 

- [x] Reseach what information can be obtained using the established communication 
- [x] Research how control commands can be send
- [x] Research how a typical communication loop handles commands and information receiving

# Acceptance criteria

This story is done when the research topic above has been done and documented on the wiki. Foto/video from hardware is required
