### ISSUE TITLE
Experimentation Custom Replay Buffer

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#172]
# Description

As developers, in order to implement the Custom Replay Buffer, we will need to experimentally develop the end solution in order to develop a Custom Replay Buffer. In other words, we will apply a test-driven development approach for creating a Custom Replay Buffer

# Why do we need to do this?

This story is needed to realize the Custom Replay Buffer for application in a real world environment, since the library it originates from - stable baselines 3 - does not support a replay buffer without a environment.

# Tasks for this user story 

- [ ] Determine success criteria for tests
- [ ] Develop fitting end solution
- [ ] Succeed all tests
- [ ] Document in project wiki

# Acceptance criteria

This user story is done when a suitable test case(s) was developed for the end-solution and a appropriate end-solution was made to satisfy the test case(s). The end-solution is also documented in the project wiki.
