### ISSUE TITLE
Update Reinforcement Learning Pipeline Diagram

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#173]
# Description

As developers, we constantly need to keep the end product of the Reinforcement Learning Pipeline up to date, as to reflect upon any new changes.

# Why do we need to do this?

This story is needed to properly document the reinforcement learning pipeline.

# Tasks for this user story 

- [x] Gather all changes to the pipeline
- [x] Create a new diagram
- [x] Upload the new diagram to the appropriate wiki pages

# Acceptance criteria

This user story is done when all references to the Reinforcement Learning Pipeline Diagram have been updated.
