### ISSUE TITLE
Implement functionality of new components from react app

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#174]
# Description
As a user I want the frontend to function as I would expect so I can actually use the frontend. All of the components need to be coupled to the api so it can actually do something. There will be changes in frontend and server code for this issue.

# Why do we need to do this?
To make the frontend actually do something.

# Tasks for this user story 
- [x] Implement api functionality.
- [x] Connect frontend to api.
- [x] fix dev dependency
- [x] Fix routing
- [x] Update wiki (https://github.com/HU-ICT-LAB/RobotWars/wiki/React-frontend)

# Acceptance criteria
This issue is completed when the tasks above are done and the wiki page for the server/api and frontend is updated.
