### ISSUE TITLE
Experimentation SAC Algorithm 

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#181]
# Description

As developers, in order to implement SAC, we will need to experimentally develop the end solution in order to develop a SAC algorithm capable of functioning without a OpenAI Gym environment. In other words, we will apply a test-driven development approach for creating the SAC algorithm class in question.

# Why do we need to do this?

This story is needed to realize the SAC for application in a “real world” environment (a simulation where we use data from the real world in reality), since the library it originates from - stable baselines 3 - does not support SAC without a environment.

# Tasks for this user story 

- [x] Determine success criteria for tests
- [x] Develop fitting end solution
- [x] Succeed all tests
- [ ] Document in project wiki

# Acceptance criteria

This user story is done when a suitable test case(s) was developed for the end-solution and an appropriate end-solution was made to satisfy the test case(s). The end-solution is also documented in the project wiki.
