### ISSUE TITLE
Make scrum document

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#183]
# Description

As students, we need to make a scrum document on how we used scrum in this project

# Why do we need to do this?

This story is needed due to the school requirements for this project

# Tasks for this user story 

- [x] Fill in the document
- [x] Grammar check the document
- [x] Sent the document to school

# Acceptance criteria

This user story is done when when the tasks above are completed
