### ISSUE TITLE
Clean up wiki and export it if possible

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#184]
# Description

As product owner, I want to have a up to date wiki and exported if possible to the school server 

# Why do we need to do this?

This story is needed to make the contractor happy and for the school requirements

# Tasks for this user story 

- [x] Check all pages if everything is filled it
- [x] Report which pages miss information or are outdated
- [x] Fix error in wiki

# Acceptance criteria

This user story is done when all tasks above are completed
