### ISSUE TITLE
Cleanup issues for next project group

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#185]
# Description

As product owner, i would like to clean up the issues list for the next group

# Why do we need to do this?

This story is needed for cleaning up the issues board for the next group

# Tasks for this user story 

- [x] Check all issues that are in the back log
- [x] Scrap issues that are no longer relivant
- [x] Add extra tag to all reasonable issues that the next group could use

# Acceptance criteria

This user story is done when the tasks above are completed
