### ISSUE TITLE
Restructure the S1-module code to an easily deployable application

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#187]
# Description

As a future developer picking up the project I would like to be able to deploy the application for the S1-module and control the robomaster S1 without having to research and reimplement certain parts of the application.

# Tasks for this user story 

- [ ] Restructure ROS2 package structure 
- [ ] Restructure Launchfile structure
- [ ] Create bashscripts for automatic Jetson initialization

# Acceptance criteria

when the tasks above are completed
