### ISSUE TITLE
Learning how to use Git-hub

### ISSUE THREAD

**Issue by The-Bimmer** [HU-ICT-LAB/RobotWars#19]
# Description

This story is about learning how to use git-hub. This is needed to learn the basics about how to use github as scrum environment .

# Why do we need to do this?

This story is needed for starting of the project with eneugh knowledge of git to get the scrum workflow going

# Tasks for this user story 

- [x] How to use markdown (.md)?
- [x] How to use the scrum method on GitHub?
- [x] How to create and use a wiki on Github?

# Acceptance criteria

This story is done when the research topic above has been done and documented on the wiki
