### ISSUE TITLE
Camera Tracking Using OpenCV

### ISSUE THREAD

**Issue by SwagLag** [HU-ICT-LAB/RobotWars#25]
# Description

This story is about tracking and detecting objects with opencv and activating some functionality of
the robomaster in the process.

# Why do we need to do this?

This story is needed understand how we can do basic image reading and responding to a image.

# Tasks for this user story 

- [x] Obtain visual feed from RoboMaster S1
- [x] Link visual feed to OpenCV
- [x] Use feedback from OpenCV to control RoboMaster S1

# Acceptance criteria

This user story is done when the RoboMaster S1 can perform actions based
on camera feedback. The code used will be documented on the wiki
