### ISSUE TITLE
Let the Robot drive via IDE controls

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#26]
# Description

This story is about controlling the robot via the ide. We want to controll the robot with simple scripts.

# Why do we need to do this?

This story is needed  to beter understand the IDE used for programming this robot for further milestones.

# Tasks for this user story 

- [x] Let the robot drive different direction with the IDE code
- [x] Let the robot aim at diffrent angles with the IDE code
- [x] Combine driving and aiming into 1 code function/script

# Acceptance criteria

This user story is down when all task above is completed and the code used is documented on the wiki
