### ISSUE TITLE
Control multiple robotmasters at the same time using 1 script

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#27]
# Description

This story is about controlling multiple robotmasters with 1 script using own code

# Why do we need to do this?

This story is needed make multi agent programming possible. We can use code from this story to create nice to have visuals for the introduction day.

# Tasks for this user story 

- [ ] Let 2 robotmasters move in sync in multiple directions
- [ ] Let 2 robotmasters aim in the same direction in sync
- [ ] Combine the above 2 function
- [ ] Let 2 robotmasters do separate function at the asme time

# Acceptance criteria

This user story is down when all the function above have been programmed and documented on the wiki
