### ISSUE TITLE
Connect Raspberry pi to the robot master

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#28]
# Description

This story is about connecting a Raspberry pi as proof of concept to connect external hardware to the robotmaster

# Why do we need to do this?

This story is needed for creating a foundation to control the robots using external hardware.

# Tasks for this user story 

- [x] Connect via hardware connection a raspberry pi to the robot using the correct connection
- [x] Get and sent data via the raspberry pi to the robotmaster
- [x] Basic control the robotmaster via a raspberry pi

# Acceptance criteria

This user story is done when the tasks above is completed and documented on the wiki
