### ISSUE TITLE
Connect a Arduino to the RobotMaster

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#29]
# Description

This story is about connecting a Arduino as proof of concept to connect external hardware to the robotmaster.

# Why do we need to do this?

This story is needed for creating a foundation to control the robots using external hardware.

# Tasks for this user story 

- [ ] Connect via hardware connection a Arduino  to the robot using the correct connection
- [ ] Get and sent data via the Arduino  to the robotmaster
- [ ] Basic control the robotmaster via a Arduino 

# Acceptance criteria

This user story is done when the tasks above is completed and documented on the wiki

**Comment by RichardDev01** [comment]
Are we still trying to connect a Arduino to the robot or is this of the chart @MatthiesBrouwer ?
