### ISSUE TITLE
Create db for data

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#30]
# Description

This story is about setting up a general database for storing data collected from the robotmaster. Data can be amount fired, times hit and other potential information that can be gather from the robotmaster.

# Why do we need to do this?

This story is needed for creating a foundation to store data for other potentional data required userstories 

# Tasks for this user story 

- [ ] Creating a requirement list for a server
- [ ] Creating a flexible infrastructure for collecting data from a robotmaster
- [ ] Make the database accessible to the rest of the project group for data analysation

# Acceptance criteria

This user story is done when the tasks above is completed and everything is documented on the wiki

**Comment by RichardDev01** [comment]
Outdated issue, closed for new issue https://github.com/HU-ICT-LAB/RobotWars/issues/87
