### ISSUE TITLE
Recognize Vision Markers on the robotmaster

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#31]
# Description

This story is about recognizing vision markers from cards that came with the robots.

# Why do we need to do this?

This story is needed for further interaction with the robot and it's envirement. This is cool for the introduction day to show it capabilities

# Tasks for this user story 

- [x] Read image from camera
- [x] Detect vision marker on an image
- [x] Read data from vision marker

# Acceptance criteria

This user story is down when the tasks above are done and the code used is documented on the wiki
