### ISSUE TITLE
Stakeholder analysation 

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#33]
# Description

This story is about making a analysis about the stakeholder of the project.

# Why do we need to do this?

This story is needed for making further userstories after the ground work is done. If we know what the stakeholder wants, we can create better goal driven sprints and deliver something that is needed.

# Tasks for this user story 

- [x] Map all the stakeholders
- [x] Put each stakeholder in a category for a more organised view.
- [x] Zooming in on our target audience
- [x] Conclusion about the goals per stakeholder

# Acceptance criteria

This user story is done when the tasks above are completed and the analysis is summarised on the wiki.
