### ISSUE TITLE
Setup workflow Github

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#36]
# Description

This story is about creating a programming workflow on github with protect branches and code control.

# Why do we need to do this?

This story is need for structuring the github branches and a reviewing stage in the progress for pull requests. This way we would have a good quality controll and a always working state of the robot in github.

# Tasks for this user story 

- [x] Setting up a code control in github (Flake8)
- [x] Setting up protected branches
- [x] Setting up a envirement for coding with requirements

# Acceptance criteria

This user story is done when the tasks above are completed and there is a short summary on github about how the workflow works
