### ISSUE TITLE
Learn how to use Flask

### ISSUE THREAD

**Issue by Rubenvdbrink** [HU-ICT-LAB/RobotWars#37]
# Description

To setup a server in python we need to use flask. 

# Why do we need to do this?

This story is needed for setting up the server.

# Tasks for this user story 

- [x] Watch flask tutorial (youtube.com/watch?v=Z1RJmh_OqeA)
- [x] Read flask documentation
- [x] Make a simple working flask application

# Acceptance criteria

This user story is done when we have a working flask request and the user story is documented.
