### ISSUE TITLE
Learn how to connect multiple RoboMasters to a single network.

### ISSUE THREAD

**Issue by Rubenvdbrink** [HU-ICT-LAB/RobotWars#4]
# Description

We need to be able to create a single point for controlling the robomasters. 

# Why do we need to do this?

This story is need for understanding how we can connect multiple robots to 1 network. We can use that for communication between the robots because that is need to play against each other or work with each other. Later on the project we can use it for agent based programming or data collection.

# Tasks for this user story 

- [x] Find a way to connect to multiple wifi devices at the same time. 
- [x] Find a way to connect to the robomasters.
- [x] Research how much bandwith is used

# Acceptance criteria

When all of the robomasters are connected to a single point like a server and this is documented in the github wiki, then this learning story can be seen as done.
