### ISSUE TITLE
Research for a method for powering a micro-controller positioned on an S1

### ISSUE THREAD

**Issue by MatthiesBrouwer** [HU-ICT-LAB/RobotWars#40]
# Description

This story is about finding a theoretical solution to power an extra micro controller positioned on a S1

# Why do we need to do this?

This story is needed for further use of a micro controller on a S1 when it is driving around. A micro controller needs powers to operate 

# Tasks for this user story 

- [x] Research existing power lines on the S1
- [x] Check if we can modify potential power lines on the S1 and what the risk are
- [x] Research the space required for a micro controller and where it can fit on a S1

# Acceptance criteria

This user story is done when we have a wiki page about the power lines on the S1 and what where we can mount a external micro controller on a S1
