### ISSUE TITLE
Use reinforcement learning to make the robot learn how to move around in the real life world

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#43]
# Description

This story is about using RL to make a S1 move around in the real world

# Why do we need to do this?

This story is needed for making the S1 make decisions on it's own while learning on how it can move around in the real world. This would be a showcase for introduction day on what AI can do in the real world

# Tasks for this user story 

- [ ] Design a train plan for the robot
- [ ] Make a work flow for RL for this subject
- [ ] Try the code a make a report of it

# Acceptance criteria

This user story is done when there is a design plan for using reinforcement learning for this subject. And there is working workflow to train the robot with manual documented on the wiki
