### ISSUE TITLE
Design a method for powering a micro-controller positioned on a S1

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#45]
# Description

This story is about creating a module/method to power a micro controller positioned on a S1. This can only be done when the arcording learning story is finished

# Why do we need to do this?

This story is needed for making a micro controller operational stand alone with it's own power source

# Tasks for this user story 

- [ ] Design (preferred in 3D) a method on how to power a micro controller positioned on a S1
- [ ] Make that design reality 
- [x] Document the process on the wiki

# Acceptance criteria

This user story is done when there is a external micro controller present on the S1 and powered stand alone. This progress should also be documented
