### ISSUE TITLE
Design a script used for the introduction day trailer

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#47]
# Description

This story is about designing a script for the video that will be used during the introduction day online. On google drive is already a template file available* 

# Why do we need to do this?

We need to do this so we can make a recording plan and check with our contractors if the content that we will be filmping, is correct.

# Tasks for this user story 

- [x] Discus with every specialty of the project team, what would represent them the most in a trailer 
- [x] Write out a recording plan with subjects to film for the video
- [x] Discus with various stake holders if we do the right thing to record

# Acceptance criteria

This user story is done when we have a script on what we want to record and the stake holders approve of it
