### ISSUE TITLE
Create a UML diagram describing the general structure of a robot module

### ISSUE THREAD

**Issue by MatthiesBrouwer** [HU-ICT-LAB/RobotWars#51]
# Description

In order to create a design for the communication structure between the server and the robot modules, first, a general structure for the robots internal functionalities has to be created.  In a later issue, this will be used for the design of the server and robot communication.

# Why do we need to do this?

To create a basis for the internal structure of the robot modules.

# Tasks for this user story 

- [x] Create a block diagram of the robot module 
- [x] Create a state diagram describing the flow of the software in broad chunks
- [x] Combine the block and state diagram into a class diagram from which the required communication structures can be references.

# Acceptance criteria

This user story is done when the communication structure can be easily referenced from the created diagrams to be used for the creation of efficient server to robot communication

**Comment by RichardDev01** [comment]
Where can i find the diagram? can you upload it to github somewhere @MatthiesBrouwer ?

**Comment by RichardDev01** [comment]
Finished
