### ISSUE TITLE
Create a first version client-websocket application to run on an RPI 

### ISSUE THREAD

**Issue by MatthiesBrouwer** [HU-ICT-LAB/RobotWars#58]
# Description

In order to test the server - client communication we need a simple client side websocket application. For now this will only serve as an example for testing purposes, but it will later be used to implement a full client-side application.

# Why do we need to do this?

To test the server side websocket communication and to use for later versions of the client side websocket application.

# Tasks for this user story 

- [x] Research websocket applications in python
- [x] Create a simple websocket client-side application
- [x] Succesfully test the client-side application with the server and establish a connection

# Acceptance criteria

This user story is done when websocket communication between an RPI client and the server is achieved
