### ISSUE TITLE
Learn how to control the RoboMaster via the app.

### ISSUE THREAD

**Issue by Rubenvdbrink** [HU-ICT-LAB/RobotWars#6]
# Description

Check how to connect to the RoboMaster with a phone/laptop for the introduction day and learning which movements the RoboMaster is capable of performing.

# Why do we need to do this?

This story is needed for knowing how the robot works out of the box and what the base features are. We can use it as inspiration for the bigger picture which is the introduction day

# Tasks for this user story 

- [x] Learn how to connect the RoboMaster with a phone.
- [x] Learn how to connect the RoboMaster with a laptop.
- [x] Learn the movements a user is capable of performing with the robomaster.

# Acceptance criteria

There is a short summary about connect with the RoboMaster for manuel controll and a short summary which describes the movements the RoboMaster is capable of performing. This will be documented on the wiki
