### ISSUE TITLE
Record videos that will be used for the introduction day

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#67]
# Description

This story is about gather video material that will be used for the introduction day

# Why do we need to do this?

This story is needed for creating video material that can be used for the introduction day 

# Tasks for this user story 

- [x] Gather AI oriented video footage 
- [x] Gather SD oriented video footage 
- [x] Gather TI oriented video footage 
- [x] Gather BIM oriented video footage 
- [x] Gather CSN oriented video footage 

# Acceptance criteria

This user story is done when there is enough footage to represent each study
