### ISSUE TITLE
Learn how to control the RoboMaster via the API.

### ISSUE THREAD

**Issue by Rubenvdbrink** [HU-ICT-LAB/RobotWars#7]
# Description

This story is about connecting to the RoboMaster via the API and controlling it through this API.

# Why do we need to do this?

This story is needed for understanding the API and it capabilties in basic form. Later on in the project, we would use this API to implement our own code which is being used on the introduction day.

# Tasks for this user story 

- [x] Learn how to connect to the RoboMaster via the API
- [x] Learn about how the RoboMaster can be controlled via the API
- [x] Perform a test using a script using the API

# Acceptance criteria

This story is done when a programmer can controll the robotmaster via an API and has documented it in the wiki.
