### ISSUE TITLE
Create and test initial ROS2 software design on microcontroller

### ISSUE THREAD

**Issue by MatthiesBrouwer** [HU-ICT-LAB/RobotWars#76]
# Description

This user story is about testing the previously designed ROS2 system on a microcontroller by implementing a simple initial version. 

# Why do we need to do this?

This will help me as a developer to further understand how the actual program should be implemented once the actual hardware arrives.

# Tasks for this user story 

- [x] Succesfully install ROS2 on a microcontroller and run the test programs
- [x] Create an initial package/node structure and establish a connection
- [x] Document the installation process and its inner workings

# Acceptance criteria

This user story is done when a successful ROS2 example process has been installed, run, and documented
