### ISSUE TITLE
Study the NVIDIA Jetson Nano and how to use it

### ISSUE THREAD

**Issue by MatthiesBrouwer** [HU-ICT-LAB/RobotWars#77]
# Description

This story is about learning how to operate an NVIDIA Jetson Nano microcontroller. This encompasses how to initialize it, how to use it (Both in software and hardware), and what it can do. This first seemed like a small task, but after searching around for a while I figured it needed to be a learning story.

# Why do we need to do this?

This story is needed in order to quickly set up and use an NVIDIA Jetson Nano without first having to read many walkthroughs and trying to understand the different SDK's from scratch. This will function as a sort of how-to guide for newcomers to the microcontroller.

# Tasks for this user story 

- [x] Research the hardware itself and the interfaces it offers
- [x] Research and document the initializing process of a Jetson Nano
- [x] Document a how-to guide on initializing and quickly using a Jetson Nano

# Acceptance criteria

This user story is done when a clear, thorough, and easy to understand guide on the Jetson Nano exists as one or more Wiki pages
