### ISSUE TITLE
Robot Tracking and Firing

### ISSUE THREAD

**Issue by SwagLag** [HU-ICT-LAB/RobotWars#79]
# Description

This story is about giving the robot the capability of tracking other robots and taking action (e.g. shooting) at the same time

# Why do we need to do this?

This story is necessary in order to enable the robot to shoot autonomously on simple triggers using the built-in
robot object detection model that we found during a previous analysis of the robot's SDK

# Tasks for this user story 

- [x] Track robots using bounding box
- [x] Control gimbal to center on target
- [x] Link firing command

# Acceptance criteria

This user story is done when the robot can autonomously track and fire upon other robots

**Comment by RichardDev01** [comment]
Where can i find the code @Max2411 or @SwagLag ?

**Comment by Max2411** [comment]
in development branch, in de experiment map, in de trackers map. De file heet robo_tracker

**Comment by RichardDev01** [comment]
Ty!
