### ISSUE TITLE
Research which database technology we're going to use.

### ISSUE THREAD

**Issue by Rubenvdbrink** [HU-ICT-LAB/RobotWars#86]
# Description
This learning story is about databases, we need to know which database suits this project the best.

# Why do we need to do this?

This story is needed for getting to know which database technology is the best option for us.

# Tasks for this user story 

- [x] Find database technologies. 
- [x] Learn about them, pro's and cons.
- [x] Compare them and pick one.

# Acceptance criteria

This user story is done when the tasks above are done and everything is documentated.
