### ISSUE TITLE
Create database beginning.

### ISSUE THREAD

**Issue by Rubenvdbrink** [HU-ICT-LAB/RobotWars#87]
# Description

This story is about making a small database beginning.

# Why do we need to do this?

We need to setup a database to save and retrieve policies and to save and retrieve findings of the robomaster.

# Tasks for this user story 

- [x] Create google account for firebase
- [x] Setup firebase
- [x] Setup firebase_admin in the backend
- [x] Create read and write functions

# Acceptance criteria

This user story is done when the tasks above are done and it is documentated.
