### ISSUE TITLE
Define policy requirements for AI Engine

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#88]
# Description

This story is about defining the policy requirements like what actions it must perform and format

# Why do we need to do this?

This story is needed to create a guideline for the AI programmers to create different types of AI components

# Tasks for this user story 

- [x] Create a actions list with data types that a policy can/must return
- [ ] ~Create a "file" format that the robot AI engine can use~
- [ ] ~Post example policy on the AI DB part~

# Acceptance criteria

This user story is done when there is a concusses about the format and it is documented on the wiki

**Comment by RichardDev01** [comment]
only documentation is required @Max2411 @Lucas-vdr-Horst
