### ISSUE TITLE
Design a way to add extra hardware to the robot

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#90]
# Description

This story is about design and place the newly acquired hardware on the robot via existing mounting places or 3D printing

# Why do we need to do this?

This story is needed to use newly acquired hardware on the robot

# Tasks for this user story 

- [x] Design something for the Jetson to assemble on the S1 
- [x] Design something for the battery to assemble on the S1
- [x] Design something for the Lidar to assemble on the S1

# Acceptance criteria

This user story is done when the ordered hardware is place on the robot and documented on the wiki
