### ISSUE TITLE
Read controller data into twist messages

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#94]
# Description

This story is about reading the controller data and making it in to twist messages

# Why do we need to do this?

This story is needed creating the ROS2 network 

# Tasks for this user story 

- [x] Research what a twist messages contain
- [x] Make a program that can read the controller data
- [x] Maken a program that transform controller data into twist messages

# Acceptance criteria

This user story is done when there are twist messages coming from the S1
