### ISSUE TITLE
Control the S1 with ROS2

### ISSUE THREAD

**Issue by RichardDev01** [HU-ICT-LAB/RobotWars#95]
# Description

This story is about controlling the S1 with ROS2

# Why do we need to do this?

This story is needed testing and creating the ROS2 network

# Tasks for this user story 

- [x] Make startup interface for the S1
- [x] Make a teleop interface
- [x] Test communication between the teleop and startup interface to control the S1

# Acceptance criteria

This user story is done when when the S1 can be controlled via ROS2
